## These functions allow a user to solve a matrix and cache the original and 
# inverse matrix. The functions can then be used to test whether a matrix has
# already been solved and retrieve the solution if so.

## This function passes a matrix and creates a list of 4 functions
# 1.Set wipes the contents of the function and starts over with y matrix as x
# 2.Get spits out the matrix x
# 3.Setinv has a function "bazooka" that solves the matrix when cacheSolve is run
# 4.Getinv spits out the inverse generated by bazooka/cacheSolve

makeCacheMatrix <- function(x = matrix()) {
        m <- NULL
        set <- function(y) { 
                x <<- y
                m <<- NULL
        }
        get <- function() {x} 
        setinv <- function(bazooka) {m <<- bazooka}
        getinv <- function() {m}
        list(get = get,
             setinv = setinv,
             getinv = getinv)
}

## This function takes the list provided by the first function and checks
# to see if an inverse matrix is cached in the "get inv" function
# If getinv is empty, the inverse is calculated and stored in the list
# If getinv contains the inverse, it returns the message and the cached inverse

cacheSolve <- function(z, ...) {
        n <- z$getinv()
        if(!is.null(n)) {
                message("getting cached data")
                return(n)
        }
        data <- z$get()
        n <- solve(data, ...)
        z$setinv(n)
        n
}

